### ISSUE TITLE
Add Vue container

### ISSUE THREAD

**Issue by supalarry** [Seluj78/PyMatcha#229]
We are transferring from React to Vue for front end.
Currently, the frontend is not running in a seperate docker container, but will so now.

Goals:
1. Integrate @supalarry front end in the Docker environment
2. Remove current frontend
3. Be able to make http request to backend container

**Comment by Seluj78** [comment]
Well you will have to transfer https://github.com/supalarry/matcha/tree/master/matcha/client to https://github.com/Seluj78/PyMatcha/tree/dev/frontend, no ?

**Comment by supalarry** [comment]
Yes, and after discussion current front end folder will be removed.
