### ISSUE TITLE
Add reset password view in frontend

### ISSUE THREAD

**Issue by supalarry** [Seluj78/PyMatcha#232]
Currently, there is only a view to request a password reset.

Goal is to add a view where user is taken after receiving reset password link.

**Comment by Seluj78** [comment]
Flow is:

- user clicks on reset password
- He enters his email and request is sent to `api:/auth/password/forgot`
- The users receives an email with a link to `web:/accounts/password/reset?token={token}`
- He enters his new password and then a request is sent to `api:/auth/password/reset`
