### ISSUE TITLE
Change Dockerfile for frontend to use production build

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/PyMatcha#263]
```
frontend      |   It seems you are running Vue CLI inside a container.
frontend      |   Access the dev server via http://localhost:<your container's external mapped port>/
frontend      | 
frontend      |   Note that the development build is not optimized.
frontend      |   To create a production build, run yarn build.
```

For now it works as we're still developping but on release we need to change the dockerfile to build the front for prod and then serve it

**Comment by supalarry** [comment]
Maybe launch vue in quet mode.

**Comment by Seluj78** [comment]
I still do think we need to change the dockerfile at the end to use the production build so we avoid some errors and remove the `vue devs tools` info in the console as well as a faster overall experience because it will be optimized.

**Comment by supalarry** [comment]
Closing this as this been implemented in final checklist PR
