### ISSUE TITLE
Clicking the Home Matcha button redirects to non signed in version

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/PyMatcha#443]
![Screenshot 2020-11-14 at 14 49 33](https://user-images.githubusercontent.com/4641317/99148559-a1fc3400-2688-11eb-89fd-455bbe756525.png)

**Comment by supalarry** [comment]
I am not sure I understand this one. With home matcha button you mean the logo in left top corner or the Get Started button?

**Comment by Seluj78** [comment]
Top left 👍
