### ISSUE TITLE
When filtering, the sliders can get confusing if you make them the same value.

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/PyMatcha#445]
![Screenshot 2020-11-14 at 14 52 25](https://user-images.githubusercontent.com/4641317/99148615-07502500-2689-11eb-82b8-cf047b2b0064.png)

Maybe change to

![Screenshot 2020-11-14 at 14 54 04](https://user-images.githubusercontent.com/4641317/99148661-40889500-2689-11eb-98a1-b8b659b5b01e.png)

**Comment by supalarry** [comment]
3rd party slider is used, so it is what it is. Good finding tho.
